import React from 'react';
import { 
  addPair,
  getBalance,
  uploadImage,
  downloadImage,
} from '../lib/api';
import { SubmitButton } from './SubmitButton/SubmitButton';
import { TextInput } from './TextInput/TextInput';
import { Container, Content, Footer, Header } from 'rsuite';
import BackIcon from '@rsuite/icons/legacy/Left';
import { useNavigate } from 'react-router-dom';

export const AddPair = (props) => {
  const navigate = useNavigate();

  const [tokenAddress, setTokenAddress] = React.useState();
  const [description, setDescription] = React.useState('');
  const [logo, setLogo] = React.useState();
  const [balance, setBalance] = React.useState('N/A');

  React.useEffect(async () => {
    getBalance('ar').then(async ret=>{
      if (ret.status === true) {
        setBalance(ret.result);
      }
    });
  }, [props.walletConnect]);

  return (
    <Container>
      <Header>
        <span onClick={()=>{navigate(`/`)}} style={{cursor: 'pointer'}}>
          {React.cloneElement(<BackIcon />, {
            style: {
              fontSize: '1.5rem',
            }
          })}
        </span>
        &nbsp;&nbsp;&nbsp;&nbsp;
        Add Pair
      </Header>
      <Container>
        <Content>
          <div className='instruction'>
            ⚠️ ThetAR exchange adheres to the concept of community autonomy - Everyone can add trading pairs. 
            At the same time, in order to avoid flooding attacks, there is a fee for adding pairs(0 $AR when it is on testnet). Your $AR balance 
            is: {balance}.
          </div>
        <TextInput 
          title='Token address:'
          tip={<>❕Note: For security, only support tokens generated by <a href='https://www.arweave.net/5llpCw0FuRUEjTCys0C_iP8icWAm2TmJYjh4tKTjTo8'>WeaveMint</a>. 
              If not, please contact <a href='mailto: marslab.2022@gmail.com'>mARsLab</a> team to add pairs for you.</>}
          onChange={setTokenAddress}
          placeholder='e.g. KmGb0DGNRfSlQzBYkHRbZYU8TEwaiNtoO-AH-ln1dJg'
        />
        <TextInput 
          title='Token description (optional):'
          tip={<>❕Note: Length should be less than 128</>}
          onChange={setDescription}
          placeholder='e.g. Token is minted via WeaveMint'
        />
        {/* <input type="file" name="file" accept='image/png, image/jpeg' onChange={changeHandler} /><img src={logo} height='1rem' width='1rem'/> */}
        <SubmitButton 
          buttonText='Submit'
          buttonSize='Medium'
          submitTask={()=>addPair(tokenAddress, description)}
        />
        </Content>
      </Container>
      <Footer><p style={{textAlign: 'center',  fontSize: '1rem'}}>©️ 2023 mARsLab</p></Footer>
    </Container>
  );
};